io:
  queueSize: 1024
  rcvBuf: 4194304
  sndBuf: 4194304
  local: false
  rst: true

workers:
  count: 2 
  queueSize: 64
  tcpMaxBufferedPagesTotal: 65536
  tcpMaxBufferedPagesPerConn: 16
  tcpTimeout: 10m 
  udpMaxStreams: 4096

replay:
  realtime: false
